### ISSUE TITLE
toaster does not work on Windows 10 version 1709

### ISSUE THREAD

**Issue by devkoriel** [mikaelbr/node-notifier#206] opened 2017-10-18 10:00 UTC
I tested the node-notifier on following environment using `npm run example:windows` command.

- Windows 10
- Version 1709
- OS Build 16299.19

However, a toast never shows up. When I test it on older version of Windows, it works perfectly.
Any others have the same issue?

**Comment by devkoriel** [comment] 2017-10-19 03:57
SnoreToast 0.5.2 probably not works on lastest version of Windows... This is the problem.

**Comment by vadim1884321** [comment] 2017-10-21 13:38
The same, I rolled back to the previous version of 1703

**Comment by devkoriel** [comment] 2017-10-23 03:42
Running SnoreToast.exe directly from command line works very fine on 1709 but `toaster.js` doesn't.

**Comment by Royalgamer06** [comment] 2017-10-29 22:57
I can confirm. I just updated Windows and no more notifications :(

**Comment by verget** [comment] 2017-11-01 13:29
I had a similar problem, solved with [anthonyraymond comment](https://github.com/mikaelbr/node-notifier/issues/144)

**Comment by Royalgamer06** [comment] 2017-11-02 12:05
Could you please be more specific in what I need to do to fix it?

**Comment by partha360** [comment] 2017-11-11 08:14
Works for me if I use 'Custompath' to 'toast' instead of 'SnoreToast'. Here is the code

```
var notifier = new WindowsToaster({
    withFallback: false, // Fallback to Growl or Balloons?
    customPath: 'C:\\Users\\<UserName>\\Downloads\\toaster\\toast\\bin\\Release\\toast.exe' // Relative/Absolute path if you want to use your fork of SnoreToast.exe
});
```

```
notifier.notify({
        title: "Title",
        message: "Message",
        wait: false, // Wait for User Action against Notification or times out. Same as timeout = 5 seconds
        appName: "app.id"

    }, function (error, response) {
        console.log(error, response);
    });
```

**Comment by md678685** [comment] 2017-11-15 22:00
By running SnoreToast manually then setting `appName: Snore.DesktopToasts`, I was able to get SnoreToast notifications working again without using a `customPath`.

**Comment by TimmoUK** [comment] 2017-11-19 09:09
Hi, I am using SnoreToast in a simple compiled batch file. After 1709, my exe never returned to my code after the SnoreToast request. The problem was resolved by stopping passing over appid. My previous code was:

snoretoast -t "NAS %nasname%" -m "Shared storage mapped to drive %drive%" -appid MapNAS -p ls-wxl.png -w

Now I am using:

snoretoast -t "NAS %nasname%" -m "Shared storage mapped to drive %drive%" -p ls-wxl.png -w

The appid in the toast message appears as SnoreToast (previously MapNAS).

**Comment by mikaelbr** [comment] 2018-01-13 21:41
This should work as expected now. Reopen if any issue

**Closed by mikaelbr** 2018-01-13 21:41 UTC
