### ISSUE TITLE
Terminal icon always shown next to notification Title (yosemite)

### ISSUE THREAD

**Issue by andre-gois** [mikaelbr/node-notifier#79] opened 2015-11-06 19:06 UTC
using electron 0.34.3 and node-notifier 4.3.1

notifications always show the terminal icons next to the Title like in this image:
![image](https://cloud.githubusercontent.com/assets/8902376/11006031/5e1a2ede-84b9-11e5-87fe-89220fb6d10b.png)

is there a way to fix this?

**Comment by kurisubrooks** [comment] 2015-11-07 00:01
Duplicate of #71. Fix is listed at the bottom.

**Closed by kurisubrooks** 2015-11-07 00:01 UTC
