### ISSUE TITLE
No notification in Windows and OS X when run in webpack for electron or node

### ISSUE THREAD

**Issue by adambowles** [mikaelbr/node-notifier#117] opened 2016-05-04 15:50 UTC
When I require and pack this with [webpack's `target`](https://webpack.github.io/docs/configuration.html#target) set to `electron`, notifications only appear in Linux.

Packing with target of `node` is the same.

I've fallen back to Electron's native implementation of desktop notifications for Mac/Windows.

**Comment by kurisubrooks** [comment] 2016-05-04 16:43
Could this be a duplicate of #94 ?

**Comment by mauri870** [comment] 2016-06-10 13:20
The same problem here with webpack on windows 10...

The error callback for the notify show this:

```
Error: spawn C:\vendor\toaster\toast.exe ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

On ubuntu works fine

**Comment by kurisubrooks** [comment] 2016-06-10 13:42
@mauri870 To me it seems like when the Notifier is spawning the Notification in a child process, it's not properly resolving the path of the Notifier. I see nothing in the code that suggests to why this happens, so i'm unsure of this. Are you spawning the notification from inside Electron? Also, is the app packed in an .asar, or with webpack ?

cc: @mikaelbr

**Comment by mauri870** [comment] 2016-06-10 13:46
Yes the notification is spawned inside electron. For dev the electron app run with a build folder generated by webpack

**Comment by kurisubrooks** [comment] 2016-06-10 13:51
It sounds like webpack is modifying the paths to the notifier, so this seems to be upstream. 
I'll leave this issue open, but leave it unconfirmed. If you find out anything, please let us know.

**Comment by mauri870** [comment] 2016-06-10 20:20
I find the solution for me, add the node config to webpack :face_with_rolling_eyes:

```
  node: {
    __filename: true,
    __dirname: true
  },
```

Thanks @kurisubrooks

**Comment by adambowles** [comment] 2016-06-10 21:43
@mauri870 I'll try that on Monday

**Comment by mikaelbr** [comment] 2016-06-10 21:46
Thanks for the awesome job in investigating and to @kurisubrooks as always for managing the issue 🎉 🍰

**Comment by kurisubrooks** [comment] 2016-06-11 01:07
Added your fix to README.md (c821adc) in hopes it'll help other people, and we can also use it as a reference to other issues should they occur. I'll close the issue when @adambowles tries the fix. 👏

**Comment by mikaelbr** [comment] 2016-07-06 11:34
How did this go, @adambowles ? Can we close it?

**Closed** 2016-07-15 08:07 UTC
Labels: Unconfirmed, Upstream
