### ISSUE TITLE
node-notifier doesn't work in Windows 10 (appID issue?)

### ISSUE THREAD

**Issue by shahar1** [mikaelbr/node-notifier#277] opened 2019-04-24 08:32 UTC
I'm trying to use node-notifier in a simple expressjs project running on Windows 10 (Webstorm IDE).
The code is plain and simple, taken from the README:

```
const notifier = require('node-notifier');
notifier.notify('Message');
```

Whatever I did - not a single message pops up. 
I tried to google it up, and it seems that I have to include an appID attribute - but I have no idea how to retrieve it (should it be for WebStorm? Command window?). Configuring it manually in the package.json doesn't work as well.

I'd appreciate any help.
Thanks in advance!

**Comment by nguiard** [comment] 2019-05-07 14:39
This works for me out of the box on Windows 10... However, if I try to get it to run via pm2 or from powershell running as system, it doesn't show any notification. Are you running it from the user you're logged in with? I don't know what could be the problem...

**Comment by shahar1** [comment] 2019-05-11 09:05
I'm running it from my user, and I'm not using either pm2 or PowerShell. 
It is indeed a mystery :)

**Comment by TotallyInformation** [comment] 2019-07-19 11:26
Not working for me either on Windows 10. Tried from PowerShell terminal under VScode and direct in a command prompt window. No errors are produced.

**Comment by peshkov3** [comment] 2019-07-24 12:31
Refused to work after updating to Windows 10 1903 verstion

**Comment by david-hollifield** [comment] 2019-08-14 15:13
I'm seeing the same thing as @peshkov3. After an update to Windows 10 1903, notifications stopped popping up. They *do* show up as notifications in the notification area after a reboot.

**Comment by jnielson94** [comment] 2019-08-16 02:56
In my testing tonight (possible I'm missing something), but it looks like it works consistently if you provide the `wait` option. Something like:
```js
const notifier = require('node-notifier')

notifier.notify({
  message: 'message',
  wait: true
})
```

That causes the notification to wait for ~10 seconds, but ensures it pops up. If you're still having issues with notifications not working on windows, throw this line before your notification:
`process.env.DEBUG="notifier"` and make sure to include at least the `[notifier options]` that it prints out and the name of the `.exe` file that it is using (you'll probably want to avoid putting the entire path to the `.exe`, but that's up to you).


Sidenote: It does look like there's a new version of [SnoreToast (the exe file used for windows), `0.6.0`](https://github.com/KDE/snoretoast) that we should probably update to. It looks like that version always waits (they took away the option [in this commit](https://github.com/KDE/snoretoast/commit/c0f25869f72f47c8bfa6936863380b9a6fe87ad8). I'm not familiar enough with the library yet to know how to update to that version of the exe file, so we'll have to wait for @mikaelbr to chime in.

**Comment by mikaelbr** [comment] 2019-08-19 09:48
@jnielson94 It's pretty straight forward to update snoretoast. Just override the exe file in `./vendors` (and the license), and check that it works as expected.

**Comment by jnielson94** [comment] 2019-08-19 13:23
Which version of the exe are we using? x86 or x64?

**Comment by mikaelbr** [comment] 2019-08-19 20:11
Honestly, I don't know: https://github.com/mikaelbr/node-notifier/pull/134. But comparing file sizes it looks like x86.

**Comment by seishun** [comment] 2019-08-26 20:46
`wait` fixes the issue for me, but it will be great if it's fixed in the module,

**Comment by 0x04** [comment] 2019-09-21 10:25
After I updated the `SnoreToast.exe` in `./vendor/snoreToast` to **v0.6.0**, I can confirm that it works again. The `wait` behavior is now default, as @jnielson94 noticed.

Don't forget to remove the `wait` parameter or you will only get the usage output from SnoreToast  🙂 That parameter should be removed in future release of `node-notifier`.

**Comment by jnielson94** [comment] 2019-09-23 17:58
@0x04 - Glad it looks to be working for you! We just released v6 a few hours ago with an updated SnoreToast version. Ideally that will fix this issue, so I'm going to go ahead and close it. Feel free to comment if you run into further issues.

**Closed by jnielson94** 2019-09-23 17:58 UTC

**Comment by seishun** [comment] 2019-09-23 18:53
It's now making sounds. Any way to disable that?

**Comment by jnielson94** [comment] 2019-09-23 18:59
@seishun - I don't think anything changed with sounds... Do you have `sound: false` in your notification? I'm pretty sure it's defaulted to true, but you should be able to turn it off.

**Comment by seishun** [comment] 2019-09-23 19:01
No, but there were no sounds before. Anyway, I turned them off through the notification settings in Windows.

**Comment by GiancarlosIO** [comment] 2019-09-27 03:26
👀
