### ISSUE TITLE
Click event not working when using NotificationCenter with custom terminal-notifier.

### ISSUE THREAD

**Issue by jmvallejo** [mikaelbr/node-notifier#147] opened 2016-11-25 16:13 UTC
I compiled my own terminal notifier to get rid of the terminal icon and put my own, now the 'click' event is not triggered.

If I remove the customPath option it works perfectly.

```js
notifier = new NotificationCenter({
    withFallback: false, // Use Growl Fallback if <= 10.8 
    customPath: path.join(__dirname, '..', 'vendor', 'terminal-notifier.app', 'Contents', 'MacOS', 'terminal-notifier')
})
```

**Comment by kurisubrooks** [comment] 2016-11-26 02:04
Did you build from julienXX or mikaelbr's repository? 
mikaelbr maintains a version of terminal-notifier that has some extra features that allows it to better integrate with node-notifier.

**Comment by jmvallejo** [comment] 2016-11-28 19:22
Hi, I forked it from mikaelbr repository, is there anything particular I should do when builing it to enable the click event? I basically changed the icon, rebuilt it and it worked (but the click event does not trigger).

Thanks in advance.

**Comment by kurisubrooks** [comment] 2016-11-29 06:24
I don't think there's anything you need to do specifically, but i'd like to get @mikaelbr's opinion on this.

**Comment by jmvallejo** [comment] 2016-11-29 20:26
Thanks, let me know how if I should provide more info or if there's anything additional I should test.

**Comment by mikaelbr** [comment] 2016-11-30 09:28
Hi! Have you tried using the master branch of `node-notifier` and the latest `terminal-notifier` from julienXX's repo?

**Comment by jmvallejo** [comment] 2016-12-01 15:18
I will give it a try!

**Comment by lauracpierre** [comment] 2016-12-26 21:17
Hi there!

I had a similar issue that drove me crazy. 

Seeing this post, I realized you are now using the original terminal-notifier version, but the version on npm is not (4.6.1).

Could you please issue a new version 4.6.2?

I can update the SO post here so that no one loses time anymore on this issue: http://stackoverflow.com/questions/35002117/remove-terminal-icon-in-node-notifier

In the meantime I'll use my own fork of node-notifier. 

Thanks !

**Comment by mikaelbr** [comment] 2016-12-26 21:27
Master branch is using the upstream terminal-notifier as it has added support for wait (and some additional features). node-notifier is awaiting a major change as it gets better JSON output from terminal-notifier, switches toaster (windows notification) and will remove CLI usage (or rewrite it, depending on what fits better).

Feel free to use your own fork of node-notifier, or use what ever fits your need best, but also remember you can install master branch of node-notifier through NPM by doing `npm install mikaelbr/node-notifier`.

**Comment by lauracpierre** [comment] 2016-12-26 22:44
Thanks @mikaelbr for the prompt response and support !

**Comment by doronsever** [comment] 2017-01-19 14:18
Hi
Any news on this issue?
I managed to change the icon with my own fork but now the click event does not work...
I'm using julienXX's terminal-notifier

**Comment by kurisubrooks** [comment] 2017-01-19 14:30
@doronsever Have you tried the version of terminal-notifier in node-notifier#master ?

**Comment by doronsever** [comment] 2017-01-19 14:33
I've installed it via NPM...
Isn't it enough?

**Comment by kurisubrooks** [comment] 2017-01-19 14:37
The version we currently have released through npm (through our repo) is not the most up to date. We still have some other pending changes before we push a new version to npm. 

I believe if you're using a custom version, i'm guessing from julienXX's repo, it should work just fine. This is currently a known bug that we're unsure of the cause, but I think the issue may be on @julienXX's end. As terminal-notifier is no longer in active development, you may have some trouble getting support though. Until we can figure out the cause of this bug I do not think there's much we can do. Sorry

cc: @mikaelbr

**Comment by julienXX** [comment] 2017-01-19 14:40
FYI terminal-notifier is still maintained and under active development even if there not many new features planned. Quite a lot of new stuff was added in the last few months. I'm not super fast on support but I'll answer your questions the best I can and when I can :)

**Comment by kurisubrooks** [comment] 2017-01-19 14:46
Ah, sorry to assume! It's been a while since I've checked your repo. Sorry for any offence I may have caused 🙏

**Comment by julienXX** [comment] 2017-01-19 14:46
No worries, just wanted to clarify that terminal-notifier is alive and well :D

**Comment by doronsever** [comment] 2017-01-19 14:47
Any way 10x for a great work for all of you!

**Comment by doronsever** [comment] 2017-01-19 15:08
I can confirm that after installing like this:

`npm install https://github.com/mikaelbr/node-notifier`

The problem stopped. At least for now...
If i encounter it again i will notify you.
10x!

**Comment by kurisubrooks** [comment] 2017-01-19 15:09
Really? Wonderful! We'll look into releasing a new version via npm soon!

cc: @mikaelbr

**Comment by lauracpierre** [comment] 2017-01-19 15:13
@dorensever last time I checked, the one caveat of doing this was that once the notifications were displayed and no action was taken (no click, just let it disappear) and then later you open the notification center on the right hand side, then the notification would not be displayed. 

But I think this was more of an issue with with terminal-notifier than node-notifier

**Comment by doronsever** [comment] 2017-01-19 15:17
@lauracpierre you are right, what you are describing still occurs.
But for me the current behavior is better then clicking on the notification and nothing happens...
I'm sure the guys will fix what you are saying soon. But now our clients can enable the silent mode on their notification center and not be disturbed.

**Comment by lauracpierre** [comment] 2017-01-19 15:21
@doronsever to have it work, do not install terminal-notifier via npm, clone directly their master branch or fork the repo. Same goes for terminal-notifier

npm versions are not necessarily up to date. and I think Mikael will be releasing a new version on npm as soon as he can :)

**Comment by doronsever** [comment] 2017-01-19 15:28
@lauracpierre are you sure? I did what you said and it doesn't work...
I cloned terminal-notifier today in order to change the icon

**Comment by mikaelbr** [comment] 2017-01-19 15:33
It's too long since I've published here. Let's make it happen. The problem is that I need to test on so many different platforms (and some I don't have access to anymore). But I'll do all updates I'm planning (new major release) and try to request some testing.

Sorry for taking so long.

**Comment by doronsever** [comment] 2017-01-19 15:35
@mikaelbr I don't mind helping you test it on mac
If you have a test list i can go over it

**Comment by lauracpierre** [comment] 2017-01-19 15:37
@doronsever yes i did this myself about a month ago. 
- clone terminal-notifier repo -> change icon, icon name in plist, build id, build-identifier and rebuild
- clone this repo from master -> specify a custom Path or add your terminal-notifier to this repo version in the vendor folder and it will work. 

@mikaelbr same goes for me, we can help

**Comment by kurisubrooks** [comment] 2017-01-19 15:38
I have access to an Ubuntu 16.04 machine I currently use as a home server, as well as a Mac that can both be tested on. Unfortunately no Windows machines though. Someone could probably spin up a VM though, right? Or maybe we could automate testing with Travis and AppVeyor?

**Comment by lauracpierre** [comment] 2017-01-19 15:39
I have that somewhere under le of dust :) Windows 10 on it.

**Comment by mikaelbr** [comment] 2017-01-19 15:41
Great. I can write some test files which we can run to verify, and also the more important test is to see if it works on existing setup.

Problem with automatic testing and regression testing here is that the project it self is such a integration based project, and the different platforms (would need a sophisticated multi-platform setup for integration tests with screenshots etc, etc). But I think if we just get some to test their existing setup/use cases, we should be good.

I'll look into finishing the v5 after dinner time. 🍽

**Comment by mikaelbr** [comment] 2017-01-19 21:22
Thats it. 21 commits later and we're closing in on a new release. I'd love for all ty try the master branch with their current setup and potentially run all examples on different environments:

```
npm run example1
npm run example2
npm run example3
```

You can install the master version by doing

```
npm i mikaelbr/node-notifier
```

See all changes and please verify changelog here: https://github.com/mikaelbr/node-notifier/blob/master/CHANGELOG.md#v500-wip

**Comment by doronsever** [comment] 2017-01-21 13:36
@lauracpierre Is there any way i can go over my settings with you?
It seems that the "wait" option is not respected. It will fire a timeout after 5 seconds even if sets to true.
What i've done for now is to set a timeout of 5 minutes

**Comment by mikaelbr** [comment] 2017-01-21 18:08
@doronsever I think maybe there's some misunderstanding around what `wait` does. `wait` doesn't make a sticky notification, it forces things like terminal-notifier til wait until response is returned. Without `wait`, it will just "fire and forget" but with `wait` it waits until timeout or user interaction.

**Comment by kurisubrooks** [comment] 2017-01-21 18:24
@mikaelbr Aah, this is confusing then. So if I understand correctly, `wait` doesn't make the notification "wait" until user action to dismiss the notification, instead it keeps node-notifier listening for a response until the notification ends?

**Comment by mikaelbr** [comment] 2017-01-21 18:28
A bit of history (if I remember correctly): In previous versions of terminal-notifier it would always exit immediately after calling the command. But to be able to listen for user interaction, I forked the terminal-notifier and added a `wait` option for it. With this, instead of exiting straight away the command waits until user has interacted with the notification. So that means the command callback in node-notifier holds until it's either timed out or activated. So it doesn't make node-notifier keep listening, strictly speaking (it always did that, but it took a short time), but it makes the command run longer.

In terminal-notifier 1.7, this wait option in built in to the upstream, so no longer need for my fork.

**Comment by kurisubrooks** [comment] 2017-01-21 18:30
Ah gotcha. We might want to add a bit of a disclaimer to the README, as even I were under the impression it were going to make the notification wait until dismissed.

**Comment by kurisubrooks** [comment] 2017-01-21 18:30
I'm not sure I could explain it as well as you can, so I might ask you to do this. (Please and thankyou!)

**Comment by mikaelbr** [comment] 2017-01-21 18:31
Sure, sure. I always thought it was implied as you could get a timeout response from the activation function, and it not being called "sticky" 💃

**Comment by doronsever** [comment] 2017-01-21 18:38
@mikaelbr is there a way to cancel the timeout event if the user is with in a reply state?(meaning he is at the middle of writing the reply)

**Comment by mikaelbr** [comment] 2017-01-21 18:40
I just added this text to the README:

> If using `reply` it's recommended to set a high timeout or no timeout at all.

This is the way `terminal-notifier` works. I could always override the timeout if reply is set, but I think letting it have default behaviour is better as in some cases you'd want timeout even with reply.

**Comment by mikaelbr** [comment] 2017-01-21 18:41
See note below example here: https://github.com/mikaelbr/node-notifier#all-notification-options-with-their-defaults

**Comment by doronsever** [comment] 2017-01-21 18:43
If I do not set a timeout at all, the timeout event if been fired after 5 seconds. 5 seconds are not enough time to write a message... so for now I set a time out of 5 minutes, but I do believe that if the user writes a reply, a timeout event should not be fired... but maybe that's only my logic

**Comment by mikaelbr** [comment] 2017-01-21 18:48
Remember `wait` is a shorthand for `timeout = 5`, so if you have `wait` it will timeout after 5 seconds. But there's no timeout necessary when using `reply` at all because `terminal-notifier` will automatically wait when it is in reply mode. Test by executing `macInput` example (`npm run example3`) and see that it doesn't timeout after 5 seconds when replying. That is when you've pressed reply. If no interaction it will disappear after 5 seconds.

**Comment by doronsever** [comment] 2017-01-21 19:02
If I don't set timeout and wait, will the reply event still be fired?

**Comment by mikaelbr** [comment] 2017-01-21 19:07
Yes. `reply: true` as options sets timeout implicitly to say "timeout in 5 seconds if the user doesn't interact with the notification. If the user clicks reply, wait until reply is sent." This is built in behaviour of `terminal-notifier` which node-notifier uses for doing notifications on Mac.

But if you don't use `reply` (that is if you just want normal notifications) and you want to listen for click. You must use timeout (that is either `wait` which is timeout 5, or explicitly set timeout for number of seconds you want for timeout)

**Comment by doronsever** [comment] 2017-01-21 20:11
Perfect! 10x

**Comment by mikaelbr** [comment] 2017-01-26 19:13
@jmvallejo Did this work out for you based on the comments in the thread?

**Closed** 2017-02-10 13:33 UTC
Labels: Bug, Confirmed, macOS

**Comment by jasonpoe** [comment] 2017-02-22 21:42
If anyone else runs across this issue, I was able to get the notification callback to fire correctly when using the customPath setting by defining an "action" in the notification config:

```javascript
const nodeNotifier = require('node-notifier');
const nc = new nodeNotifier.NotificationCenter({
  customPath: 'path/to/my/custom/notifier'
});

nc.notify({
      title: 'My Title',
      message: 'My body',
      actions: 'View' // action or reply must be defined for callback to be fired
      //reply: true - does not work when actions are defined
    },  function (error, responseType, metadata) {
       console.log('callback fired with correct responseType / metadata');
    }
));
```

Without an action or reply defined, the callback is immediately invoked when the notification is shown.  

I'm currently using https://github.com/julienXX/terminal-notifier for my custom notifier.
