### ISSUE TITLE
Notifications don't spawn under certain macOS environments

### ISSUE THREAD

**Issue by fean** [mikaelbr/node-notifier#47] opened 2015-02-28 14:33 UTC
Well, it doesn't seem to work. I'd like to use your notification plugin for my nodeJS tool for OS X. There seem to be no errors or any indications that something went wrong, the notifications just do not show up. When I launch the terminal-notifier.app in the vendor folder it caughs up a nice notification. So that isn't the problem.
I've tried the following things:

``` javascript
var notifier = require('node-notifier');

notifier.notify({
        title: 'Now playing',
        subtitle: track.name,
        message: track.artist
    });
```

And I've tried this:

``` javascript
var notifier = require('node-notifier');

notifier.notify({
        title: 'Now playing',
        message: track.name + ' - ' + track.artist
    });
```

And this, even though I don't want the notifications to show up in the notification center:

``` javascript
var nn = require('node-notifier');
var notifier = new nn.NotificationCenter();

notifier.notify({
        title: 'Now playing',
        subtitle: track.name,
        message: track.artist
    });
```

I've installed it from the `npm` and are trying to use it in combination with `NW.js` or previously known as `node-webkit`.

**Comment by adam-lynch** [comment] 2015-02-28 19:53
Just pointing out the obvious, but have you seen https://github.com/nwjs/nw.js/wiki/Notification ?

**Comment by fean** [comment] 2015-02-28 23:34
Thank you for your reponse. Yes, I've seen that. We're using a lot of native modules that do not run under the newer versions of node. That is why we run version 0.8.6 of `NW.js` and why we were looking at your plugin for notifications.

**Comment by mikaelbr** [comment] 2015-03-22 20:03
Do you get any errors? Other people using NW.js/node-webkit have reported that there might be an issue with permissions.

**Comment by fean** [comment] 2015-03-23 13:20
No it fails very gracefully. The notification just doesn't show up. Even if I use the `terminal-notifier.app`.

**Comment by fean** [comment] 2015-03-23 13:23
Well, when I called the `terminal-notifier.app` from my terminal to test the switches it work just fine. But calling it from within the `NW.js` didn't seem to work.

**Comment by mikaelbr** [comment] 2015-03-23 18:32
Have you tried looking at the error object in the callback? 

```js
notifier.notify({
  message: 'Message!'
}, function (err, response) {
  console.log(err);
});
```

**Comment by lozandier** [comment] 2015-04-07 22:13
Same problem; running the latest version of Yosemite, and any attempt to get a toaster doesn't work…

## Setup Information
I'm using `iojs` version `1.6.4`, Node version `0.12`, and I'm using node-notifier version `4.1.2.`on a maxed-out '14 Macbook Pro. 

## Example of my attempt to use `node-notifier`
```js
var notifier = require(node-notifier);
// …

gulp.task('build', ['optimize', 'images', 'fonts'], function(){
  // Didn't need gulp-notify in this case
  var msg = {
    title: 'Building files',
    subtitle: 'Deployed to the build folder',
    message: 'Running gulp serve-build'
  };
  del(config.temp);
  log(msg);
  notify(msg);
});


function notify(options){
  var notifyOptions = {
    sound: 'Bottle',
    contentImage: path.join(__dirname, 'gulp.png'),
    icon: path.join(__dirname, 'gulp.png')
  };
  _.assign(notifyOptions, options);
  console.log(notifyOptions);
  notifier.notify(notifyOptions);
}


```

**Comment by mikaelbr** [comment] 2015-04-08 10:20
I now tried the following from a clean install:

```js
var path = require('path');
var notifier = require('node-notifier');

if (!Object.assign) {
  Object.defineProperty(Object, 'assign', {
    /* Object.assign polyfill here */
  });
}

function notify(options){
  var notifyOptions = {
    sound: 'Bottle',
    contentImage: path.join(__dirname, 'gulp.png'),
    icon: path.join(__dirname, 'gulp.png')
  };
  Object.assign(notifyOptions, options);
  notifier.notify(notifyOptions);
}

notify({ message: 'hello' });
```

And ran:
```shell
$ nvm use iojs
Now using io.js v1.6.3
$ npm i node-notifier
node-notifier@4.1.2 node_modules/node-notifier
├── which@1.0.9
├── shellwords@0.1.0
├── clone@0.1.19
├── growly@1.2.0
└── semver@4.3.3
$ node index.js
```

On the latest Yosemite (with Notification Center activated), and it works for me. Have you tried adding a callback for seeing the error?

Instead of your line:
```js
  notifier.notify(notifyOptions);
```

do 
```js
  notifier.notify(notifyOptions, function (error) { console.log(error); });
```

**Comment by lozandier** [comment] 2015-04-08 16:05
@mikaelbr 

Still using iojs version `1.6.4`, your recommended change to my calls of `notifier` with a `function(error){ console.log(error);` added as a second parameter got `node-notifier` to *work*. 

Did I misunderstood your well documented plugin to always add a error callback as a second callback to get `node-notify` to work? 

No actual errors were logged in my console; that said, it seems the notifications do not fire after one or two runs of a task; subsequent runs of the same tasks do not have the notifications fire for some strange reason…

```js

function notify(options){
  var notifyOptions = {
    sound: 'Bottle',
    contentImage: path.join(__dirname, 'gulp.png'),
    icon: path.join(__dirname, 'gulp.png')
  };
  _.assign(notifyOptions, options);
  console.log(notifyOptions);
  notifier.notify(notifyOptions, function(error){ console.log(error); });
}

// Other use of node-notifier that fired only once

gulp.task('styles', gulp.series('clean-styles', function(){
  log('Compiling Less --> CSS');
  notifier.notify({ message: 'Yo' }, function(error){ console.log(error); });

  return gulp.src(config.less)
  .pipe($.plumber())
  .pipe($.less())
  // .on('error', errorLogger)
  .pipe($.autoprefixer({browser: ['last 2 version', '> 5%']}))
  .pipe(gulp.dest(config.temp))
}));


```

**Comment by kurisubrooks** [comment] 2015-10-16 08:09
Hey @fean, just wondering if you ever got it working?

**Comment by kurisubrooks** [comment] 2015-10-21 19:42
It's now been a week since asking for an update, but as I have not received a reply, I am going to close this issue for now. If the problem is still apparent, please let me know and i'll be glad to look into this again for you.

**Comment by kumar303** [comment] 2017-01-04 23:30
I probably shouldn't even post this (out of shame) but I will anyway: check to make sure notifications aren't completely disabled in System Preferences 👞 👖 💥 . I got stuck on it because there was no error in the callback, which would have been helpful. It's not really an error though.

**Comment by kurisubrooks** [comment] 2017-01-05 10:33
Hi @kumar303, could I get your OS, OS version and node-notifier version please?

**Comment by kumar303** [comment] 2017-01-05 15:22
Oh, is that not expected behavior? I'm on Mac OS X 10.10.5 using node-notifier 4.6.1, node 6.3.0

**Comment by kurisubrooks** [comment] 2017-01-05 15:30
You shouldn't require a callback in order for the function to work. Unfortunately if our module doesn't give you an error we really aren't sure what we can do about it until we can reproduce it for ourselves.

Because you're on macOS I don't think there are any awaiting changes to be pushed through npm, so it looks like this bug is still in effect.

@kumar303 Could I possibly see what the exact code you're using to trigger the notification is?

**Comment by kumar303** [comment] 2017-01-05 15:36
> You shouldn't require a callback in order for the function to work.

That's not the case for me. It works both with and without the callback.

My code is nothing out of the ordinary. I was doing this:

````javascript
import notifier from 'node-notifier';
notifier.notify({title: 'some title', message: 'some message'});
````

Once I enabled notifications in System Preferences, I saw the notification :) While it was disabled, the callback (not shown here) did not receive an `error` or a `response` -- both were empty. This was confusing to me because I didn't know why I couldn't see any notifications. However, it seems like expected behavior in hindsight.

**Comment by kumar303** [comment] 2017-01-05 15:37
I only added to this bug thread because it was the first one I found when googling for a solution 💰

**Comment by kurisubrooks** [comment] 2017-01-05 15:47
Ah, gotcha. Sorry, I think I misread your question. I'm unsure if there's anything we can hook into in the system to see if Notifications are disabled though, but it's worth looking into. Thanks!
cc: @mikaelbr

**Closed by kurisubrooks** 2017-01-05 15:47 UTC
Labels: Can't Reproduce, Confirmed, Help Wanted, macOS

**Comment by shadymoses** [comment] 2020-01-15 21:51
I'm running into this issue, and this is the error I'm getting:
<img width="701" alt="Screen Shot 2020-01-15 at 2 33 09 PM" src="https://user-images.githubusercontent.com/6036045/72473493-066a1080-37a4-11ea-98ea-b74f65cd4152.png">

It's likely an issue with our setup, but I'm not sure where. These assets are compiled with webpack, and I added the recommended snippet to my webpack config:
```javascript
node: {
  __filename: true,
  __dirname: true,
}
```
These bundled assets are loaded in an nwjs app, so maybe there's something going on there? If anyone has any ideas on what the issue might be, that would be much appreciated.

**Comment by Amethystafyy282** [comment] 2022-04-29 03:26
> 

Happening to me, too. macOS 11.3, node 14.17.3

**Comment by Amethystafyy282** [comment] 2022-04-29 03:26
> I'm running into this issue, and this is the error I'm getting: <img alt="Screen Shot 2020-01-15 at 2 33 09 PM" width="701" src="https://user-images.githubusercontent.com/6036045/72473493-066a1080-37a4-11ea-98ea-b74f65cd4152.png">
> 
> It's likely an issue with our setup, but I'm not sure where. These assets are compiled with webpack, and I added the recommended snippet to my webpack config:
> 
> ```js
> node: {
>   __filename: true,
>   __dirname: true,
> }
> ```
> 
> These bundled assets are loaded in an nwjs app, so maybe there's something going on there? If anyone has any ideas on what the issue might be, that would be much appreciated.
> 
> I'm on macOS 10.15.2 and node 10.16.0.

Happening to me, too. macOS 11.3, node 14.17.3
