### ISSUE TITLE
503 Service Unavailable - node-notifier-5.4.5.tgz

### ISSUE THREAD

**Issue by abhikakade** [mikaelbr/node-notifier#443] opened 2024-06-06 16:15 UTC
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-5.4.5.tgz: Request failed \"503 Service Unavailable\"".

tried with npm registry as well getting same error every time.

**Comment by duduc** [comment] 2024-06-21 14:02
i have the same issue

**Comment by mikaelbr** [comment] 2024-06-26 07:01
I think yarn registry is a mirror for npm registry and this was caused by service issues on npm. Seems to work as expected now?

**Comment by mikaelbr** [comment] 2024-10-30 21:25
Closing as no update

**Closed as completed by mikaelbr** 2024-10-30 21:25 UTC
