### ISSUE TITLE
Windows run example no response

### ISSUE THREAD

**Issue by liudonghua123** [mikaelbr/node-notifier#208] opened 2017-10-21 04:06 UTC
When I run the example on Win10 16299.19, none of the example response.

![image](https://user-images.githubusercontent.com/2276718/31847918-26098c06-b658-11e7-891a-f09362d0fbe5.png)

And I also run the test.

![image](https://user-images.githubusercontent.com/2276718/31847925-4594ea02-b658-11e7-8f66-d49c05904962.png)

Any ideas?

**Comment by mikaelbr** [comment] 2017-10-21 06:29
Hi! This might be app-id issue. Try providing `appID`:

notifier.notify({
  message: 'Hello!',
  appID: 'my-app'
});

If that doesn't work, try running https://github.com/KDE/snoretoast directly and see if that works.

**Comment by liudonghua123** [comment] 2017-10-21 07:41
@mikaelbr It still not works!

![image](https://user-images.githubusercontent.com/2276718/31849522-51315f1c-b676-11e7-81c0-642126a0c6df.png)

**Comment by arjun-g** [comment] 2017-10-24 04:00
Same here. After the Fall Creators Update in my Windows 10 system notifications stopped working. Working on other systems though.

**Comment by mikaelbr** [comment] 2017-10-24 10:47
Ok. It looks like Windows might have changed its notification API. We need to update [snoretoast](https://github.com/KDE/snoretoast) to make it work

**Comment by MikeKovarik** [comment] 2017-10-25 13:52
I can confirm, I even tried directly SnoreToast's CLI and it does not work in the fall creators update.

**Comment by sgehrman** [comment] 2017-11-02 10:21
stopped working for me too.

**Comment by mikaelbr** [comment] 2017-11-02 10:22
Can anyone with this version of Windows try to fix the issue with snoretoast? I don't have access to this Windows at the current time.

**Comment by Alecto** [comment] 2017-11-05 20:57
i have the same problem at all my computers under W10

**Comment by xdisplayx** [comment] 2017-11-07 16:50
"Can anyone with this version of Windows try to fix the issue with snoretoast? I don't have access to this Windows at the current time."

What a pilgrim excuse!
https://www.virtualbox.org/
https://www.microsoft.com/es-mx/software-download/windows10

**Comment by xdisplayx** [comment] 2017-11-07 16:55
"Can anyone with this version of Windows try to fix the issue with snoretoast? I don't have access to this Windows at the current time."

What a pilgrim excuse!
https://www.virtualbox.org/
https://www.microsoft.com/es-mx/software-download/windows10

**Comment by xdisplayx** [comment] 2017-11-07 17:10
"Can anyone with this version of Windows try to fix the issue with snoretoast? I don't have access to this Windows at the current time."

What a pilgrim excuse!
https://www.virtualbox.org/
https://www.microsoft.com/es-mx/software-download/windows10

**Comment by mikaelbr** [comment] 2017-11-07 17:19
Context to @xdisplayx's comment here: https://github.com/mikaelbr/gulp-notify/issues/120

**Comment by qubicle** [comment] 2017-11-08 11:08
Windows seems to be more specific with the submitted appID. it's actually not a problem with snoretoast. that works fine. Your appID has to be the same as registered with the install.
In my case squirrel registered the appID which had 
**com.squirrel.***
in front of my id.

**Comment by mikaelbr** [comment] 2017-11-08 11:11
@qubicle  Oh. Nice. Do you mind writing a small note in the docs for how to fix it (what appID to use etc)?

**Comment by partha360** [comment] 2017-11-13 03:14
Notifier works for me,
- Windows 10
- Version 1709
- OS Build 17025.1000

I use 'Custompath' to 'toast' instead of 'SnoreToast'. Here is the code

```
var notifier = new WindowsToaster({
    withFallback: false, // Fallback to Growl or Balloons?
    customPath: 'C:\\Users\\<UserName>\\Downloads\\toaster\\toast\\bin\\Release\\toast.exe'
});
```

```
notifier.notify({
        title: "Title",
        message: "Message",
        wait: false,
        appName: "app.id"

    }, function (error, response) {
        console.log(error, response);
    });
```
Note the use of appName instead of appID.

**Comment by MikeKovarik** [comment] 2017-11-13 14:46
That's more of a hack, rather than fix

**Comment by mikaelbr** [comment] 2017-11-13 21:37
@MikeKovarik It looks like the fix is to use proper `appId` as @qubicle is saying.

**Comment by sgehrman** [comment] 2017-11-14 02:44
I'm calling this in my package.json when a build finishes.  What is my appID or appName or whatever. I can't get it working.

**Comment by partha360** [comment] 2017-11-14 03:36
I am using the appId as defined in package.json
`{
  "name": "some-name",
  **"appId": "app.id",**
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "node-notifier": "^5.1.2"
  },
  "devDependencies": {
    "eslint": "^4.11.0",
    "eslint-config-google": "^0.9.1",
    "puppeteer": "^0.12.0"
  }
}
`

**Comment by partha360** [comment] 2017-11-14 03:38
@mikaelbr reason I used Toaster instead of SnoreToast and with latest Win 10 build there were some API changes. Yes it is more of a hack, I will update back to SnoreToast and see if it still works.

**Comment by Frioo** [comment] 2017-11-18 18:41
Windows 10 Pro (Fall Creators Update), no errors but also no notification - I am using node notifier in a single-file script, what should I set my appId to?

**Comment by stefanhill** [comment] 2017-11-21 16:09
Same situation as @Frioo here, Win10 1709 build 16299.64
no errors but also no notification, using node notifier

**Comment by FrancisBou** [comment] 2017-12-06 14:55
I made sure my appId was correct and I'm still having the issue, Win 10 1709.

**Comment by enzy** [comment] 2017-12-14 12:47
`appId` is not usable solutions for pure npm modules. There is no installation process (specific to Windows) therefore no `appId`. Can we bypass this or at least make automatic id generation?

**Comment by hstarorg** [comment] 2018-01-13 08:11
Same too, when will fix it?

**Comment by mikaelbr** [comment] 2018-01-13 11:52
This should be fixed in master branch now, by removing default appId as it seems to cause errors in newest Windows. It works as expected again on a fresh Windows with me.

**Comment by hstarorg** [comment] 2018-01-13 15:59
@mikaelbr Very thanks, it's work in my win10(version1709, 16299.192)

**Comment by mikaelbr** [comment] 2018-01-13 17:01
New version published. Should be fixed. Reopen if not.

**Closed by mikaelbr** 2018-01-13 17:01 UTC
Labels: Hacktoberfest, Help Wanted

**Comment by mpalu** [comment] 2018-01-13 21:44
Working here now.
