### ISSUE TITLE
Notifications are not appearing on Windows 8+ when I distribute the app.

### ISSUE THREAD

**Issue by lipis** [mikaelbr/node-notifier#75] opened 2015-10-08 12:30 UTC
The app and notifications work perfectly on my development machine (Windows 10) and in my Notification settings I have something like this: 

![screen shot 2015-10-08 at 13 34 31](https://cloud.githubusercontent.com/assets/125676/10366177/ee913a8c-6dc8-11e5-9143-9d44f1ced41d.png)

And when I'm disabling the `toast` app there are no more notifications. But when I'm trying it on another machine (Windows 8.1 for example) there are no notifications and no `toast` in the Notifications. Am I missing something?

(I integrated the node-notifier with Electron)

**Comment by lipis** [comment] 2015-10-08 13:53
I have the following code: 
```js
  notifier.notify({
    title: title,
    message: message,
    sound: false,
    wait: true,
    data: data, // custom data
  }, function(error, response) {
    console.log('error', response);
    raygunClient.send(new Error('Notifier Error'), {error, response});
  });
```

here is the stacktrace and error if it's helpful:

```bash
    WindowsToaster.[anonymous] in C:\Users\User\AppData\Local\wire\app-2.2417\resources\app.asar\main.js:97
    unknown.[anonymous] in C:\Users\User\AppData\Local\wire\app-2.2417\resources\app.asar\node_modules\node-notifier\lib\utils.js:165
    unknown.[anonymous] in C:\Users\User\AppData\Local\wire\app-2.2417\resources\app.asar\node_modules\node-notifier\lib\utils.js:53
    ChildProcess.ChildProcess.exithandler in child_process.js:222
    Object.emitTwo in events.js:87
    ChildProcess.ChildProcess.emit in events.js:172
    Object.maybeClose in internal/child_process.js:817
    Process.Process.ChildProcess._handle.onexit in internal/child_process.js:211
```

```
error: {
  killed: false
  code: 3762504530
  signal: undefined
  cmd: "C:\Users\User\AppData\Local\Temp\7EEA.tmp -sound false -data [object Object] -m foo -t bar -q true -w true"
}
response: ""
```

**Comment by kurisubrooks** [comment] 2015-10-11 15:10
Are you using Electron? I'm having a similar problem in #76

**Comment by lipis** [comment] 2015-10-13 09:22
I'm using the [grunt-electron](https://github.com/sindresorhus/grunt-electron) (which is using the [electron-packager](https://github.com/maxogden/electron-packager)) and when I'm adding the `asar: false` then I'm getting the following error:

![screen shot 2015-10-13 at 11 15 10](https://cloud.githubusercontent.com/assets/125676/10450726/7e1f5414-719c-11e5-9353-abf512a94781.png)

So I might have to wait for the asar support as well :/

**Comment by kurisubrooks** [comment] 2015-10-13 09:25
The problem doesn't look to be with the packager, but because the file name is too long. Try shortening the file name to something like `squirrel-installer` and try to re-run the build.

**Comment by kurisubrooks** [comment] 2015-10-13 09:26
If this doesn't work, let me know and i'll try to run you through using electron-packager by itself.

**Comment by kurisubrooks** [comment] 2015-10-13 09:38
Duplicate of #76

**Closed by kurisubrooks** 2015-10-13 09:38 UTC
Labels: Bug, Duplicate

**Comment by lipis** [comment] 2015-10-13 09:40
You are right it's the [grunt-electron-installer](https://github.com/atom/grunt-electron-installer) problem and I can see that the path or the file name or both are two long and that's why I put the whole thing in the root.. not sure if I can do anything more..

**Comment by lipis** [comment] 2015-10-13 09:45
Changed the build directories.. but the same error: 
![screen shot 2015-10-13 at 11 44 51](https://cloud.githubusercontent.com/assets/125676/10451355/ebaa2664-719f-11e5-945d-50b6b432f0d2.png)

**Comment by kurisubrooks** [comment] 2015-10-13 09:46
Can you try running the command with `--force`? Let me know if that gives any errors.

**Comment by lipis** [comment] 2015-10-13 10:34
Not much..

**Comment by kurisubrooks** [comment] 2015-10-13 10:35
If you want, you could try running it through [electron-packager](https://github.com/maxogden/electron-packager) in the command line.
https://github.com/maxogden/electron-packager#usage
