### ISSUE TITLE
Module not found: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by vkolova** [mikaelbr/node-notifier#192] opened 2017-08-10 18:44 UTC
I'm getting
```
./~/node-notifier/lib/utils.js
Module not found: Can't resolve 'child_process' in '[project_dir]\node_modules\node-notifier\lib'
```
 error whenever I try to use node-notifier. I'm using Node v6.11.2 and the code is copy-paste from the examples. Any ideas? I tried manually instaling the dependencies, because I noticed they're not installed, but it didn't help.

**Comment by mikaelbr** [comment] 2017-08-10 20:27
Hi! Are you trying to start this through node or something else like the browser? `child_process` is a built in module in Node and there shouldn't be any reason for you not to find it.

The format of your path (specifically the `./~/` part) suggests to me that you are using some bundler or transpiler on the code and/or that you try to execute it from a browser. Maybe webpack? If this is the case, it won't work I'm afraid. This is a node package only, and will not work in the browser.

**Comment by vkolova** [comment] 2017-08-10 20:39
I'm trying to start it though node. Yes, I am using webpack(I added the mentioned stuff in the readme) and babel, in an Electron app. So.. it wont work at all? :/

**Comment by mikaelbr** [comment] 2017-08-10 20:47
When using Webpack with a node project (or electron) you have to take some action for setting webpack _not_ to resolve some of the built in packages, by marking them as external. See for instance here: https://github.com/webpack/webpack/issues/744

**Comment by vkolova** [comment] 2017-08-11 18:45
Okay, I'm kind of ashamed to post again, but I really want to use Notifier. Sorry.
I managed to get rid of all errors, but.. I can't seem to get it working. I guess I'm missing something with the configuration of Webpack. Currently my settings are:
`   node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'mock',
    __filename: true,
    __dirname: true
  },
  externals: [
    'ws'
  ],
  target: 'electron'`
I also tried a demo I found and it worked fine. Anyone that has used it with create-react-app?

**Comment by mikaelbr** [comment] 2017-08-11 19:32
Hi. I'm really no expert in the combination of Webpack and Electron, but try setting `child_process` to `false` or `empty` instead. I don't think `mock` sound quite right.

**Comment by vkolova** [comment] 2017-08-11 20:24
I tried both options - no change :/

**Comment by vkolova** [comment] 2017-08-16 17:48
No one has any info on the issue?

**Comment by mikaelbr** [comment] 2018-01-14 10:51
Maybe check this out: https://github.com/webpack/webpack.js.org/issues/107

As far as node-notifier, I don't think there is anything we can do, so I'm closing. Feel free to repoen if you think otherwise.

**Closed by mikaelbr** 2018-01-14 10:51 UTC

**Comment by Asma-Projects** [comment] 2018-04-18 14:44
just put in package.json 
 "browser":{
"child_process": false
}

**Comment by rishishrivastav321** [comment] 2018-08-24 10:45
I was also facing the same issue. 
The mistake that I was doing was, instead of importing the NgModule from @angular/core, I was importing it from @angular/cli.

So soon as corrected it, its started executing.

**Comment by princeivankent** [comment] 2019-02-06 02:09
> just put in package.json
> "browser":{
> "child_process": false
> }

**Comment by MrBandaruk** [comment] 2019-02-13 03:13
I've just faced with the same issue!
I was trying to import my service using wrong path. -_-

_Double check import paths._

**Comment by Worthy7** [comment] 2019-03-04 04:19
Yep, same here. I was `import { EventEmitter } from 'selenium-webdriver';`
Instead from from `@angular/core`

**Comment by kmturley** [comment] 2021-01-03 01:55
In my case I was importing a simple method which seemingly had only client-side code:

`import { clientSideMethod } from 'mypackage'`

clientSideMethod() lives in :

`./node_modules/mypackage/dist/utils.js`

But the error came from a completely different file:

```
Module not found: Can't resolve 'child_process'
error - ./node_modules/mypackage/dist/file.js:8:0
```

It seems that using a generic package import, traverses all files underneath regardless of whether the methods are actually called:

`import { clientSideMethod } from 'mypackage'`

Actually first goes to the root index.js of the package and calls:

```
export * from './file'; // contains server-side code
export * from './utils'; // contains client-side code only
```

Therefore the error was triggered. Solutions are:

1. Use a more specific import import { clientSideMethod } from '../../node_modules/mypackage/dist/utils'
2. Dynamically import server-side modules when needed
3. Split packages or modules into client-side vs server-side

Very simple to fix, but frustrating to find the cause!
