### ISSUE TITLE
Mac Notification Center w/ wait and group

### ISSUE THREAD

**Issue by leigeber** [mikaelbr/node-notifier#64] opened 2015-08-07 16:31 UTC
We are running node-notifier 4.2.3 on Yosemite 10.10.4 and not having any luck with the group or wait parameters, everything else works as expected. Here is the configuration object being passed into `notifier.notify()`.

``` javascript
{
  title: 'JSCS Validation Error',
  message: 'Check console for error details',
  icon: 'node_modules/wee-core/build/img/error.png',
  group: 2,
  sound: true,
  wait: true
}
```

This immediately replaces a notification with group 1 and auto-hides after a couple seconds instead of waiting for interaction. Is there a known issue or does anything seem off? Thanks.

**Comment by kurisubrooks** [comment] 2015-09-12 17:22
These parameters aren't supported for OS X as far as i'm aware. The `wait` flag is supported on Windows and Linux, but there's nothing in the documentation for OS X. 

These flags are supported on OS X: `title`, `subtitle`, `message`, `sound`, `appIcon`, `contentImage`, `open`

**Comment by mikaelbr** [comment] 2015-09-14 05:45
Hi! OS X actually support the `wait` flag. The `terminal-notifier` vendor files included is a [fork of the original, with support for wait](https://github.com/mikaelbr/terminal-notifier/commit/0dd8abb403f7ddfb08985ba883308819b9a07085).

**Comment by kurisubrooks** [comment] 2015-09-14 06:32
I just tried testing, and I can't get `wait` to work either. It still auto hides after a while. I'm on El Capitan, incase that's important.

**Comment by kurisubrooks** [comment] 2015-09-14 07:01
Just wondering, in your code you say `-WAIT YES`, is that the syntax, or is it `wait: true`?
I've been using the latter.

**Comment by mikaelbr** [comment] 2015-09-14 07:03
`wait: true` should be fine. "Yes" is true in Objective C.

**Comment by kurisubrooks** [comment] 2015-09-14 07:04
Ah I see. If that's the case, i'm afraid to say it's not working for me :(

**Comment by mikaelbr** [comment] 2015-09-14 07:06
It might be a regression issue, on a update on `terminal-notifier` (as in when terminal-notifier was updated, the fork code got lost). I'll have to check what version is used.

**Comment by mikaelbr** [comment] 2015-10-13 20:52
I've investigated this, and looked through the terminal-notification code and tried to make this work. But no luck I'm afraid. As far as I can tell, it might be changed behaviour in the Notification Center, as `group` in terminal-notifier is used to just remove existing notifications that has current `group`. I couldn't find a way to do this, even though it seems as [`identifier` in `NSUserNotificationCenter`](https://developer.apple.com/library/prerelease/mac/documentation/Foundation/Reference/NSUserNotification_Class/index.html#//apple_ref/occ/instp/NSUserNotification/identifier) should do what we want it doesn't seem to work.

**Comment by mikaelbr** [comment] 2015-10-13 20:53
I still can't reproduce missing `wait`.

**Comment by mikaelbr** [comment] 2015-10-14 05:56
Related: https://github.com/mikaelbr/node-notifier/issues/55#issuecomment-147899662

**Comment by kurisubrooks** [comment] 2015-10-14 07:10
@mikaelbr just had a thought, would it be possible to change the notification type to the "Open, Close" kind of notification that sticks, if the wait flag is present? I've googled around a bit and can only seem to find that you are manually able to change the notification type to the "Alert" type from the settings. Is there a way to do this in Objective C?

**Comment by mikaelbr** [comment] 2015-10-14 07:41
I tested some around this yesterday. There is two ways to do this: either by changing the settings on each machine, or changing a setting in the plist file in the app that does the notification (terminal-notifier). I'm investigating the possibility to extend `terminal-notifier` to have action buttons and even reply text, but that's a different issue.

**Comment by mikaelbr** [comment] 2016-04-12 14:08
As far as I found out, the Notification Center API didn't respond well to the group functionality. Tried extending terminal-notifier, but no luck. I'm afraid this has to be a wontfix until some other solution can be found.

**Comment by prietoguy** [comment] 2016-06-02 16:35
So just to confirm, there is no way currently to make a notification wait for user interaction on OS X?

When I run this:

```(javascript)
const notifier = require('node-notifier');

notifier.notify({
    'title': 'Title',
    'message': 'Message',
    'open': 'https://google.com',
    'wait': true
  }, function(error, response) {
    console.log(response);
});
```

 I get `timeout` as the response. Do you use `notifyutil`? If so would passing an `-w` argument do the trick?

**Comment by mikaelbr** [comment] 2016-07-06 11:33
This should work when having `wait: true`, but it is not grouping. You should only get timeout if no interaction with the notification.

**Comment by hhff** [comment] 2016-12-02 18:39
I'm unable to get `wait` to work on iOS at all.  The Notification disappears after 5 seconds regardless of what I try.

```
import NodeNotifier from 'node-notifier';

let notifier = new NodeNotifier.NotificationCenter();
return notifier.notify({
  'title': 'my notification',
  'message': 'hello',
   'wait': true,
})
```

Is this related to this thread?  If so - what is the work around for notifications that stay until clicked?

**Comment by kurisubrooks** [comment] 2016-12-03 03:32
@hhff This module is unsupported for React Native and other mobile frameworks. node-notifier is only available for macOS, Linux (various distros), and Windows 7+

**Comment by hhff** [comment] 2016-12-03 20:10
Apologies @kurisubrooks  - I was tired when I wrote the above message - I am using OSX (not iOS, that's a typo)

**Comment by kurisubrooks** [comment] 2016-12-04 08:28
Hmm. Worth looking into. @mikaelbr

**Comment by clayton93** [comment] 2017-01-10 12:12
Like @hhff I am unable to get any sticky notifications (Alerts as opposed to Banners) on Mac OS X. I am running macOS Sierra.

**Comment by mikaelbr** [comment] 2017-01-10 12:14
Is this something that is supported by [terminal-notifier](https://github.com/julienXX/terminal-notifier)? In that case, try testing out the master branch, if not I'm afraid it's an issue for terminal-notifier, not node-notifier.

**Comment by mikaelbr** [comment] 2017-01-19 21:05
Closing this for now.

**Closed by mikaelbr** 2017-01-19 21:05 UTC
Labels: Bug, Can't Fix, Confirmed, macOS

**Comment by luciomr** [comment] 2019-10-22 20:13
For anyone interested, the wait time of a notification doesn't depend on a script (AppleScript/osascript) or an app. 
OSX handles this in System Preferences -> Notifications -> choose terminal-notifier from the list on the left, and on the right, instead of **banners**, choose **alerts**.
I got the tip from [an answer on stackexchange](https://apple.stackexchange.com/a/214598/264826).
